# Generated by Django 4.2.11 on 2025-08-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail',
        ),
    ]
